baseURL = "https://rohitshinde.in"
languageCode = "en-US"
title = "Rohit Shinde"
author = "Rohit Shinde"
theme = "hugo-bearblog"


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  title = "Rohit Shinde"
  description = "Personal website of Rohit Shinde"
  copyright = "Copyright © 2024"
  dark = "off"
  highlight = true
  hideMadeWithLine = true

[menu]
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   title = "posts"
  #   url = "/"
  #   weight = 10

  # [[menu.main]]
  #   identifier = "about"
  #   name = "about"
  #   title = "about"
  #   url = "/about/"
  #   weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true


[markup.highlight]
      codeFences = true
      hl_Lines = ""
      lineNoStart = 1
      lineNumbersInTable = true
      tabWidth = 4
      style="solarized-light"
      pygmentsUseClasses = true
      pygmentsCodefences = true
