baseURL = "http://example.org"
languageCode = "en-US"
title = ""
theme = "hugo-bearblog"


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  description = "Personal website of Rohit Shinde"
  copyright = "Copyright © 2021"
  dark = "off"
  highlight = true

[menu]
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   title = "posts"
  #   url = "/"
  #   weight = 10

  # [[menu.main]]
  #   identifier = "about"
  #   name = "about"
  #   title = "about"
  #   url = "/about/"
  #   weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

